// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: payment.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (external_id, currency, total_amount, status, message, memo, expires_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, external_id, currency, total_amount, status, message, memo, expires_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ExternalID  sql.NullString `json:"external_id"`
	Currency    string         `json:"currency"`
	TotalAmount int64          `json:"total_amount"`
	Status      PaymentStatus  `json:"status"`
	Message     sql.NullString `json:"message"`
	Memo        sql.NullString `json:"memo"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.queryRow(ctx, q.createPaymentStmt, createPayment,
		arg.ExternalID,
		arg.Currency,
		arg.TotalAmount,
		arg.Status,
		arg.Message,
		arg.Memo,
		arg.ExpiresAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Currency,
		&i.TotalAmount,
		&i.Status,
		&i.Message,
		&i.Memo,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentDestination = `-- name: CreatePaymentDestination :one
INSERT INTO payment_destinations (payment_id, destination, amount, percentage, total_amount, discount_amount, apply_bonus, max_bonus_amount, max_bonus_percentage)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING payment_id, destination, amount, percentage, total_amount, discount_amount, apply_bonus, max_bonus_amount, max_bonus_percentage
`

type CreatePaymentDestinationParams struct {
	PaymentID          uuid.UUID     `json:"payment_id"`
	Destination        string        `json:"destination"`
	Amount             sql.NullInt64 `json:"amount"`
	Percentage         sql.NullInt16 `json:"percentage"`
	TotalAmount        int64         `json:"total_amount"`
	DiscountAmount     int64         `json:"discount_amount"`
	ApplyBonus         bool          `json:"apply_bonus"`
	MaxBonusAmount     int64         `json:"max_bonus_amount"`
	MaxBonusPercentage int16         `json:"max_bonus_percentage"`
}

func (q *Queries) CreatePaymentDestination(ctx context.Context, arg CreatePaymentDestinationParams) (PaymentDestination, error) {
	row := q.queryRow(ctx, q.createPaymentDestinationStmt, createPaymentDestination,
		arg.PaymentID,
		arg.Destination,
		arg.Amount,
		arg.Percentage,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.ApplyBonus,
		arg.MaxBonusAmount,
		arg.MaxBonusPercentage,
	)
	var i PaymentDestination
	err := row.Scan(
		&i.PaymentID,
		&i.Destination,
		&i.Amount,
		&i.Percentage,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.ApplyBonus,
		&i.MaxBonusAmount,
		&i.MaxBonusPercentage,
	)
	return i, err
}

const deletePaymentDestinations = `-- name: DeletePaymentDestinations :exec
DELETE FROM payment_destinations WHERE payment_id = $1
`

func (q *Queries) DeletePaymentDestinations(ctx context.Context, paymentID uuid.UUID) error {
	_, err := q.exec(ctx, q.deletePaymentDestinationsStmt, deletePaymentDestinations, paymentID)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, external_id, currency, total_amount, status, message, memo, expires_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.queryRow(ctx, q.getPaymentStmt, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Currency,
		&i.TotalAmount,
		&i.Status,
		&i.Message,
		&i.Memo,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByExternalID = `-- name: GetPaymentByExternalID :one
SELECT id, external_id, currency, total_amount, status, message, memo, expires_at, created_at, updated_at FROM payments WHERE external_id = $1::VARCHAR
`

func (q *Queries) GetPaymentByExternalID(ctx context.Context, externalID string) (Payment, error) {
	row := q.queryRow(ctx, q.getPaymentByExternalIDStmt, getPaymentByExternalID, externalID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Currency,
		&i.TotalAmount,
		&i.Status,
		&i.Message,
		&i.Memo,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentDestinations = `-- name: GetPaymentDestinations :many
SELECT payment_id, destination, amount, percentage, total_amount, discount_amount, apply_bonus, max_bonus_amount, max_bonus_percentage FROM payment_destinations WHERE payment_id = $1
`

func (q *Queries) GetPaymentDestinations(ctx context.Context, paymentID uuid.UUID) ([]PaymentDestination, error) {
	rows, err := q.query(ctx, q.getPaymentDestinationsStmt, getPaymentDestinations, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentDestination
	for rows.Next() {
		var i PaymentDestination
		if err := rows.Scan(
			&i.PaymentID,
			&i.Destination,
			&i.Amount,
			&i.Percentage,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.ApplyBonus,
			&i.MaxBonusAmount,
			&i.MaxBonusPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET status = $1 WHERE id = $2 RETURNING id, external_id, currency, total_amount, status, message, memo, expires_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	Status PaymentStatus `json:"status"`
	ID     uuid.UUID     `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.queryRow(ctx, q.updatePaymentStatusStmt, updatePaymentStatus, arg.Status, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Currency,
		&i.TotalAmount,
		&i.Status,
		&i.Message,
		&i.Memo,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
